/* -- DATOS DE PRUEBA
Script con: 8 usuarios (5 regulares + 3 agentes), 4 categorías, 30 tickets en diferentes estatus y
prioridades, y 60 comentarios.*/

--Categroías
INSERT INTO categorias (nombre) VALUES
('Facturación'),
('Soporte Técnico'),
('Accesos'),
('Otro');

--Usuarios
INSERT INTO usuarios (nombre, email, rol) VALUES
('Yoleisy Arteaga',      'yoleisy.arteaga@empresa.com', 'Usuario'),
('Osvaldo López',  'osvaldo.lopez@empresa.com', 'Usuario'),
('Yaleidy Trujillo',     'yaleidy.trujillo@empresa.com', 'Usuario'),
('Roberto Sánchez', 'roberto.sanchez@empresa.com', 'Usuario'),
('Sofía Ramírez',   'sofia.ramirez@empresa.com', 'Usuario'),
('Eyleen de Leon',   'eyleen.de.leon@soporte.com', 'Agente'),
('Vivian Luisa',     'vivian.luisa@soporte.com', 'Agente'),
('Balder López',     'balder.lopez@soporte.com', 'Agente'); 


--30 tickets con diferentes combinaciones de estatus, prioridad, categorías y asignaciones.
INSERT INTO tickets (titulo, descripcion, categoria_id, prioridad, estatus, creado_por, asignado_a, fecha_creacion, fecha_resolucion) VALUES
('No puedo acceder al portal',               'Mi usuario no tiene acceso desde ayer.',                     3,'urgente', 'en_progreso',1,6, NOW()-INTERVAL '5 days',  NULL),
('Error en factura del mes de octubre',      'La factura muestra un cobro duplicado.',                     1,'alta',    'abierto',    2,NULL,NOW()-INTERVAL '4 days',  NULL),
('PC no enciende tras actualización',        'Mi equipo no inicia después de actualizar Windows.',         2,'alta',    'en_progreso',3,7, NOW()-INTERVAL '3 days',  NULL),
('Solicitud de nueva contraseña',            'Olvidé mi contraseña y el enlace de recuperación expiró.',  3,'media',   'resuelto',   4,6, NOW()-INTERVAL '7 days',  NOW()-INTERVAL '6 days'),
('VPN se desconecta constantemente',         'La conexión VPN cae exactamente cada 10 minutos.',           2,'urgente', 'en_progreso',5,8, NOW()-INTERVAL '2 days',  NULL),
('Cobro incorrecto en plan Premium',         'Se me cobró tarifa básica en lugar de Premium.',             1,'alta',    'abierto',    1,NULL,NOW()-INTERVAL '1 day',   NULL),
('Impresora de red piso 3 no responde',      'La impresora compartida del piso 3 no aparece en red.',     2,'media',   'en_progreso',2,7, NOW()-INTERVAL '6 days',  NULL),
('Acceso a carpeta compartida denegado',     'Error de permisos al acceder a \\servidor\proyectos.',      3,'media',   'abierto',    3,NULL,NOW()-INTERVAL '2 days',  NULL),
('Correos rebotan al enviar',                'Los correos enviados desde mi cuenta no llegan.',            2,'alta',    'en_progreso',4,8, NOW()-INTERVAL '3 days',  NULL),
('Consulta descuento por volumen',           'Quiero saber si hay descuento para 20 licencias.',           4,'baja',    'resuelto',   5,6, NOW()-INTERVAL '10 days', NOW()-INTERVAL '9 days'),
('Monitor con líneas verticales verdes',     'Monitor Dell muestra líneas verdes intermitentes.',          2,'baja',    'abierto',    1,NULL,NOW()-INTERVAL '1 day',   NULL),
('No se puede exportar reporte a PDF',       'El botón de exportar PDF no hace nada al dar clic.',         2,'media',   'en_progreso',2,7, NOW()-INTERVAL '4 days',  NULL),
('Error 500 en módulo de pagos',             'Al hacer clic en Pagar aparece error 500.',                  2,'urgente', 'en_progreso',3,8, NOW()-INTERVAL '1 day',   NULL),
('Facturación duplicada en enero',           'Recibí dos facturas idénticas por el mismo periodo.',        1,'alta',    'resuelto',   4,6, NOW()-INTERVAL '15 days', NOW()-INTERVAL '14 days'),
('Alta de usuario nuevo',                    'Necesito acceso para el empleado Juan Ruiz.',                3,'media',   'cerrado',    5,7, NOW()-INTERVAL '20 days', NOW()-INTERVAL '19 days'),
('Adobe Illustrator no inicia',             'Illustrator cierra inmediatamente al abrir.',                2,'media',   'abierto',    1,NULL,NOW()-INTERVAL '3 days',  NULL),
('Código SMS de autenticación no llega',     'El SMS de 2FA no llega a mi celular.',                       3,'alta',    'en_progreso',2,8, NOW()-INTERVAL '2 days',  NULL),
('Solicitud de reembolso suscripción',       'Quiero reembolso de mi suscripción anual.',                  1,'alta',    'abierto',    3,NULL,NOW()-INTERVAL '1 day',   NULL),
('Teclado inalámbrico sin respuesta',        'El teclado dejó de funcionar sin motivo aparente.',          2,'baja',    'cerrado',    4,7, NOW()-INTERVAL '25 days', NOW()-INTERVAL '24 days'),
('Error en cálculo de horas extra',          'El sistema calcula incorrectamente las horas extra.',        4,'alta',    'en_progreso',5,6, NOW()-INTERVAL '3 days',  NULL),
('Sin acceso al sistema de nómina',          'Error de permisos al intentar entrar a nómina.',             3,'urgente', 'abierto',    1,NULL,NOW()-INTERVAL '6 hours', NULL),
('Licencia de antivirus expirada',           'El antivirus muestra aviso de licencia vencida.',            2,'media',   'resuelto',   2,8, NOW()-INTERVAL '12 days', NOW()-INTERVAL '11 days'),
('Factura sin RFC del receptor',             'Mi factura electrónica no incluye mi RFC.',                  1,'media',   'abierto',    3,NULL,NOW()-INTERVAL '2 days',  NULL),
('Proyector sala de juntas falla con HDMI',  'El proyector no reconoce la laptop por HDMI.',               2,'baja',    'resuelto',   4,7, NOW()-INTERVAL '8 days',  NOW()-INTERVAL '7 days'),
('No puedo restablecer PIN de seguridad',    'El enlace de restablecimiento de PIN expiró.',               3,'media',   'en_progreso',5,6, NOW()-INTERVAL '4 days',  NULL),
('Lentitud extrema en ERP',                  'El sistema ERP tarda más de 5 minutos en cargar.',           2,'urgente', 'en_progreso',1,8, NOW()-INTERVAL '2 days',  NULL),
('Duda sobre política de cancelación',       'Quiero saber si puedo cancelar sin penalización.',           4,'baja',    'cerrado',    2,6, NOW()-INTERVAL '30 days', NOW()-INTERVAL '29 days'),
('Cámara web no detectada en Zoom',          'Zoom no detecta la cámara web integrada.',                   2,'baja',    'abierto',    3,NULL,NOW()-INTERVAL '1 day',   NULL),
('Error al generar CFDI',                    'El sistema no genera el XML del CFDI correctamente.',        1,'urgente', 'en_progreso',4,7, NOW()-INTERVAL '5 hours', NULL),
('Solicitud de permisos de administrador',   'Necesito instalar software corporativo autorizado.',         3,'media',   'abierto',    5,NULL,NOW()-INTERVAL '3 days',  NULL);


--60 comentarios variados en contenido, distribuidos en los tickets.
INSERT INTO comentarios (ticket_id, autor_id, contenido, fecha, es_interno) VALUES
(1, 6, 'Revisando los permisos del usuario en Active Directory.',                    NOW()-INTERVAL '4 days 20 hours', TRUE),
(1, 1, '¿Cuánto tiempo estimado tomará la resolución?',                              NOW()-INTERVAL '4 days 18 hours', FALSE),
(1, 6, 'Aproximadamente 2 horas. El problema es una política de grupo restrictiva.', NOW()-INTERVAL '4 days 16 hours', TRUE),
(1, 8, 'Revisión cruzada: también hay problema con el grupo de seguridad regional.', NOW()-INTERVAL '4 days 14 hours', TRUE),
(2, 2, '¿Podrían revisar específicamente la factura F-2024-0213?',                   NOW()-INTERVAL '3 days 22 hours', FALSE),
(2, 6, 'Escalando al equipo de facturación para revisión urgente.',                  NOW()-INTERVAL '3 days 20 hours', TRUE),
(3, 7, 'Se actualizó el driver de video. Por favor reinicia y confirma.',            NOW()-INTERVAL '2 days 22 hours', FALSE),
(3, 3, 'Reinicié pero el equipo sigue sin iniciar correctamente.',                   NOW()-INTERVAL '2 days 20 hours', FALSE),
(3, 7, 'Agendaremos revisión física del equipo mañana a las 10am.',                  NOW()-INTERVAL '2 days 18 hours', TRUE),
(3, 8, 'Equipo en lista de reemplazo según inventario Q1-2026.',                     NOW()-INTERVAL '2 days 16 hours', TRUE),
(4, 6, 'Se envió enlace de restablecimiento al correo registrado.',                  NOW()-INTERVAL '6 days 12 hours', FALSE),
(4, 4, 'Ya pude acceder con la nueva contraseña. Muchas gracias.',                   NOW()-INTERVAL '6 days 10 hours', FALSE),
(5, 8, 'Revisando configuración de timeout en servidor VPN.',                        NOW()-INTERVAL '1 day 22 hours', TRUE),
(5, 5, 'El problema persiste, se desconecta exactamente a los 10 minutos.',          NOW()-INTERVAL '1 day 20 hours', FALSE),
(5, 8, 'Es un idle timeout. Aplicando parche de configuración esta noche.',          NOW()-INTERVAL '1 day 18 hours', TRUE),
(5, 6, 'Relacionado con el cambio de infraestructura VPN del mes pasado.',           NOW()-INTERVAL '1 day 16 hours', TRUE),
(6, 1, 'El cargo aplicado es $599 pero el plan Premium debería ser $999.',           NOW()-INTERVAL '22 hours', FALSE),
(6, 7, 'Verificando en el sistema de pagos el cargo aplicado al usuario.',           NOW()-INTERVAL '20 hours', TRUE),
(7, 7, 'Se reinició el servicio de spooler de impresión. Probando conectividad.',    NOW()-INTERVAL '5 days 20 hours', TRUE),
(7, 2, 'Imprime de forma intermitente, a veces funciona y otras no.',                NOW()-INTERVAL '5 days 18 hours', FALSE),
(9, 8, 'Revisando registros SPF y DKIM del dominio corporativo.',                    NOW()-INTERVAL '2 days 22 hours', TRUE),
(9, 4, 'Es muy urgente, tengo una propuesta comercial pendiente de enviar.',         NOW()-INTERVAL '2 days 20 hours', FALSE),
(9, 6, 'DNS propagándose. Debería resolverse en menos de 1 hora.',                   NOW()-INTERVAL '2 days 18 hours', TRUE),
(10, 6,'Sí aplica descuento del 15% a partir de 10 licencias. Le envío cotización.', NOW()-INTERVAL '9 days 12 hours', FALSE),
(10, 5,'Perfecto, muchas gracias por la información.',                                NOW()-INTERVAL '9 days 10 hours', FALSE),
(12, 7,'Revisando módulo de exportación. Es un bug conocido en esta versión.',       NOW()-INTERVAL '3 days 20 hours', TRUE),
(12, 2,'¿Tienen estimado de cuándo se liberará el fix?',                             NOW()-INTERVAL '3 days 18 hours', FALSE),
(13, 8,'Error 500 por timeout en pasarela de pago. Notificando al proveedor.',       NOW()-INTERVAL '22 hours', TRUE),
(13, 3,'Tenemos ventas perdidas por esto, necesitamos solución inmediata.',          NOW()-INTERVAL '20 hours', FALSE),
(13, 6,'Coordinando con DevOps para rollback si no se resuelve en 2 horas.',        NOW()-INTERVAL '18 hours', TRUE),
(14, 6,'Reembolso procesado por cargo duplicado. Referencia: REF-2026-045.',         NOW()-INTERVAL '14 days 10 hours', FALSE),
(14, 4,'Confirmo recepción del reembolso. Muchas gracias.',                          NOW()-INTERVAL '14 days 8 hours', FALSE),
(17, 8,'El operador reporta saturación. Sugiero usar app autenticadora.',            NOW()-INTERVAL '1 day 22 hours', FALSE),
(17, 2,'Ya configuré Google Authenticator como alternativa. Funciona bien.',         NOW()-INTERVAL '1 day 20 hours', FALSE),
(20, 6,'Revisando script de cálculo. Error detectado en manejo de días festivos.',   NOW()-INTERVAL '2 days 22 hours', TRUE),
(20, 5,'Afecta a 15 empleados del departamento de operaciones.',                     NOW()-INTERVAL '2 days 20 hours', FALSE),
(20, 8,'Notificando a RH para corrección manual mientras se libera el fix.',         NOW()-INTERVAL '2 days 18 hours', TRUE),
(22, 8,'Licencia renovada y desplegada automáticamente via WSUS.',                   NOW()-INTERVAL '11 days 10 hours', FALSE),
(22, 2,'Confirmado, el antivirus ya muestra licencia activa hasta 2027.',            NOW()-INTERVAL '11 days 8 hours', FALSE),
(24, 7,'Cable HDMI defectuoso. Se reemplazó con uno nuevo del almacén.',             NOW()-INTERVAL '7 days 10 hours', FALSE),
(24, 4,'Funciona perfectamente con el cable nuevo. Gracias por la rapidez.',         NOW()-INTERVAL '7 days 8 hours', FALSE),
(25, 6,'Verificando en AD los grupos de seguridad asignados al usuario.',            NOW()-INTERVAL '3 days 22 hours', TRUE),
(25, 5,'¿Hay algún avance? El acceso es urgente para mis actividades.',              NOW()-INTERVAL '3 days 20 hours', FALSE),
(26, 8,'Analizando queries lentas con pg_stat_statements.',                          NOW()-INTERVAL '1 day 22 hours', TRUE),
(26, 1,'Impacta a toda la operación, necesitamos solución urgente hoy.',             NOW()-INTERVAL '1 day 20 hours', FALSE),
(26, 8,'Identificadas 3 queries sin índices. Aplicando optimización.',               NOW()-INTERVAL '1 day 18 hours', TRUE),
(29, 7,'Generando CFDI manualmente mientras se investiga el bug.',                   NOW()-INTERVAL '4 hours', TRUE),
(29, 4,'Necesito el XML antes de las 5pm para cerrar la contabilidad del mes.',      NOW()-INTERVAL '3 hours', FALSE),
(29, 7,'CFDI generado manualmente. XML enviado al correo registrado.',               NOW()-INTERVAL '2 hours', FALSE),
(8,  3,'La ruta de la carpeta es \\servidor\proyectos\2026.',                        NOW()-INTERVAL '1 day 22 hours', FALSE),
(11, 1,'El modelo exacto es Dell U2722D, adquirido hace 8 meses.',                   NOW()-INTERVAL '22 hours', FALSE),
(16, 1,'El error ocurre específicamente en Illustrator versión 28.0.0.',             NOW()-INTERVAL '2 days 22 hours', FALSE),
(18, 3,'El cargo fue hace 3 días: $4,800 MXN por licencia anual.',                  NOW()-INTERVAL '22 hours', FALSE),
(21, 1,'El mensaje de error exacto es: "No tiene permiso para este recurso".',      NOW()-INTERVAL '5 hours', FALSE),
(23, 3,'El RFC correcto del receptor es ABCD123456EF7.',                             NOW()-INTERVAL '1 day 22 hours', FALSE),
(28, 3,'La cámara es Logitech C920. Funciona en otros programas pero no en Zoom.',   NOW()-INTERVAL '22 hours', FALSE),
(30, 5,'El software es el IDE corporativo aprobado por IT en la lista blanca.',      NOW()-INTERVAL '2 days 22 hours', FALSE),
(15, 7,'Usuario creado y accesos configurados correctamente en todos los sistemas.', NOW()-INTERVAL '19 days 10 hours', FALSE),
(15, 5,'Juan ya puede acceder sin problemas. Cerrando el ticket.',                   NOW()-INTERVAL '19 days 8 hours', FALSE),
(27, 6,'Política de cancelación: sin penalización si cancelas dentro de 30 días.',   NOW()-INTERVAL '29 days 10 hours', FALSE),
(19, 7,'Teclado reemplazado con unidad nueva del inventario de repuestos.',          NOW()-INTERVAL '24 days 10 hours', FALSE);